#!/bin/bash
# mpg321all
# Convert a whole list of mp3's to wav's.

if [ ! -n "$1" ]
then 
	echo "Usage: `basename $0` file1.mp3 file2.mp3 etc."
	exit 1
fi

for args in "$@"
do
	filename="${args%.*}"
	extension="${args##*.}"
	lower_extension="${extension,,}"
	
	case "$lower_extension" in
		"mp3"	) 
			mpg123 -v --stereo -w "${filename}.wav" "$args" 
			;;
		"flac" )
			echo "running flac -d $args"
			flac -d "$args"
			;;
	esac

done

exit 0
