#!/bin/bash
# Edit a file that has been encoded with gpg.

function usage {
	echo "Usage: $0 FILE"
}

function die {
	echo $1

	exit 1
}

# make sure there is only one argument
if [ "$#" != "1" ]
then
	usage
	exit 1
fi

file_name=$1

# make sure the argument is a file
[[ -f $file_name ]] || die "ERROR! $file_name is not a file."

# get us a temp file
temp_file=`mktemp`

# read in password

read -s -p "Password: " password
echo 

# unencrypt the file and put it's output in tempfile
echo $password | gpg --passphrase-fd 0 -d ${file_name} > ${temp_file} || 
	die "ERROR! Could not decrypt $file_name"

# edit the tempfile
$EDITOR ${temp_file} || 
	die "ERROR! Could not edit the decrypted file ${temp_file}"

# reencrypt the tempfile
echo $password | gpg --passphrase-fd 0 -c -o ${file_name} ${temp_file} || 
	die "ERROR! Could not reencrypt ${temp_file} to ${file_name}."

# delete the tempfile
rm ${temp_file}
