#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

# load in user resources
userresources=$HOME/.Xresources

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

# swap ctrl and caps
swap_caps_ctrl_xmodmap="$HOME/.Xmodmap_swap_ctrl_caps"

if [ -f "$swap_caps_ctrl_xmodmap" ]; then
    xmodmap "$swap_caps_ctrl_xmodmap"
fi

# change keys on Japanese keyboard if we are using a Japanese keyboard
japanese_keyboard_xmodmap="$HOME/.Xmodmap_japanese_keyboard"

if [ -f "$swap_caps_ctrl_xmodmap" ]; then
	grep_output=$(lsusb | grep '045e:00dc Microsoft Corp.')
	if [ -n "$grep_output" ] ; then
		xmodmap "$japanese_keyboard_xmodmap"
	fi
fi


export LC_ALL="ja_JP.UTF-8"
export LANG="ja_JP.UTF-8"
export XMODIFIERS="@im=ibus"
export XMODIFIER="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"

export TERM="xterm-256color"

ibus-daemon -x &

/usr/bin/wmacpi &

eval `ssh-agent`
xterm -e ssh-add &

# set both screens
#xrandr --output LVDS1 --auto --primary --output VGA1 --left-of LVDS1 --rate 75 --size 1024x768
if [ "$(xrandr | grep -o "DVI-I-1 connected")" == "DVI-I-1 connected" ] 
then 
	#xrandr --output LVDS-1 --auto --primary --output DVI-I-1 --left-of LVDS-1 --mode "1024x768"
	#xrandr --output LVDS-1 --auto --primary --pos 0x600 --output DVI-I-1 --rotate left --pos 1920x0
	xrandr --output LVDS-1 --auto --primary --pos 0x600 --output DVI-I-1 --rotate left --pos 1920x0 --mode "1920x1080"
fi

exec fluxbox

