#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
xinitdir=/usr/X11R6/lib/X11/xinit
sysresources=$xinitdir/.Xresources
sysmodmap=$xinitdir/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

#export LC_ALL="ja_JP.UTF8"
#export LANG="ja_JP.UTF8"
export XMODIFIERS="@im=ibus"
export XMODIFIER="@im=ibus"
export GTK_IM_MODULE="ibus"
export QT_IM_MODULE="ibus"

export TERM="xterm-256color"

ibus-daemon -x &

wmapci &

eval `ssh-agent`
xterm -e ssh-add &

# set both screens
#xrandr --output LVDS1 --auto --primary --output VGA1 --left-of LVDS1 --rate 75 --size 1024x768
if [ "$(xrandr | grep -o "DVI-I-1 connected")" == "DVI-I-1 connected" ] 
then 
	xrandr --output LVDS-1 --auto --primary --output DVI-I-1 --left-of LVDS-1 --mode "1024x768"
fi

exec fluxbox

