#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
xinitdir=/usr/X11R6/lib/X11/xinit
sysresources=$xinitdir/.Xresources
sysmodmap=$xinitdir/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
    xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
    xmodmap $usermodmap
fi

#export LC_ALL="ja_JP.UTF8"
#export LANG="ja_JP.UTF8"
export LC_CTYPE="ja_JP.UTF8"
export XMODIFIERS="@im=SCIM"
export XMODIFIER="@im=SCIM"
export GTK_IM_MODULE="scim"
export QT_IM_MODULE="scim"

LANGUAGE="C" scim &

#conky &


eval `ssh-agent`
xterm -e ssh-add &

#xrandr --output LVDS --auto --output VGA --auto

exec fluxbox

#LD_LIBRARY_PATH=/usr/lib/opengl/xorg-x11/lib/ \
#beryl --replace dbus settings &
#emerald &


