#!/bin/sh

# This is the .xprofile setup script that SLiM uses to launch the window manager.

# setup dbus
# test for an existing bus daemon, just to be safe
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
	# if not found, launch a new one
	eval `dbus-launch --sh-syntax`
fi


# xmonad needs the cursor set
xsetroot -cursor_name left_ptr

export TERM="xterm-256color"
#export LC_ALL="ja_JP.UTF-8"
#export LANG="ja_JP.UTF-8"

#export XMODIFIERS="@im=fcitx"
#export XMODIFIER="@im=fcitx"
#export GTK_IM_MODULE="fcitx"
#export QT_IM_MODULE="fcitx"
#fcitx &

eval `ssh-agent`
xterm -e ssh-add &

