#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

# Setup dbus.
# This is needed for gtk applications like evince.
# Test for an existing bus daemon, just to be safe.
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
	# if not found, launch a new one
	eval `dbus-launch --sh-syntax`
fi

# load in user resources
userresources=$HOME/.Xresources
if [ -f $userresources ]; then
	xrdb -merge $userresources
fi

# swap ctrl and caps with xmodmap
#swap_caps_ctrl_xmodmap="$HOME/.Xmodmap_swap_ctrl_caps"
#if [ -f "$swap_caps_ctrl_xmodmap" ]; then
#	( sleep 3 && xmodmap "$swap_caps_ctrl_xmodmap" ) &
#fi

# swap left control and caps lock
#setxkbmap -option ctrl:swapcaps
# make caps lock a control key
#setxkbmap -option ctrl:nocaps

# set some environment variables
export TERM="xterm-256color"
#export LC_ALL="ja_JP.UTF-8"
#export LANG="ja_JP.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

# load fcitx
export XMODIFIERS="@im=fcitx"
export XMODIFIER="@im=fcitx"
export GTK_IM_MODULE="fcitx"
export QT_IM_MODULE="fcitx"
fcitx &

# network manager applet
nm-applet &

# redshift
# (NOTE: doesn't really work when you are offline.  So I am leaving it hard
# coded for now.)
redshift-gtk -l 35:140 &

# stalonetray
stalonetray &

# screensaver
/usr/bin/xscreensaver -no-splash &

# add ssh keys
eval `ssh-agent`
xterm -e ssh-add &
#ssh-add "$HOME/.ssh/awsworkprivatekeypair2.pem" &

# xrandr settings
#xrandr-setup-screens --startup

# startup syndaemon.  This disables the synaptics touchpad for two seconds
# after every keypress.  This stops me from accidentally making the mouse
# click when I am typing.
syndaemon -t -K &

# startup xmonad
xmonad &
windowmanagerpid=$!
wait $windowmanagerpid
